main:
  - name: Contact
    url: /contact/
    weight: 1

  - name: About Site
    url: /about-site/
    weight: 7

  - name: Posts
    url: /posts/
    weight: 3

  - name: Hobbies
    url: /hobbies/
    weight: 4

  - name: Projects
    url: /projects/
    weight: 5

  - name: Resume
    url: /resume/
    weight: 2

  - name: Skills
    url: /skills/
    weight: 6

  #- name: Certifications
  #  url: /certifications/
  #  weight: 8

  #- name: Why me?
  #  url: /why-me/
  #  weight: 9

  # - name: Docs
  #   url: /docs/
  #   weight: 11

#     about-site contact posts hobbies projects resume skills certifications why-me?
